export const BaseUrl = process.env.NODE_ENV === 'production' ? `https://${process.env.DEPLOY_DOMAIN}` : 'http://localhost:3000'
export const ChatUrl = process.env.CHAT_URL 
 
export const spaceTypes: string[] = [
    "Apartment",
    "Arena",
    "Art Gallery",
    "Atrium",
    "Auditorium",
    "Ballroom",
    "Bar",
    "Basketball Court",
    "Black Box",
    "Boardroom",
    "Bowling Alley",
    "Cabaret",
    "Café",
    "Car Park",
    "Chapel",
    "Church",
    "Classroom",
    "Clubhouse",
    "Colosseum",
    "Conference Room",
    "Courtyard",
    "Covered Outdoor Space",
    "Cruise",
    "Dance Studio",
    "Dining Hall",
    "Dining Room",
    "Drill Hall",
    "Event Space",
    "Exhibit Hall",
    "Exterior of Building",
    "Fieldhouse",
    "Foyer",
    "Gallery",
    "Garden",
    "Greenroom",
    "Gym",
    "Hall",
    "Hangar",
    "Hotel",
    "Ice Rink",
    "Island",
    "Kitchen",
    "Library",
    "Lobby",
    "Locker Room",
    "Loft",
    "Lounge",
    "Meeting Room",
    "Museum",
    "Music Hall",
    "National Park",
    "Nightclub",
    "Office",
    "Outdoor",
    "Park (Private)",
    "Park (Public)",
    "Patio",
    "Pavilion",
    "Penthouse",
    "Performance Hall",
    "Pier",
    "Plaza",
    "Pool Deck",
    "Pop Up Space",
    "Pre-Function",
    "Public Plaza",
    "Raw",
    "Reception Hall",
    "Reception Room",
    "Red Carpet Area",
    "Restaurant",
    "Retail Space",
    "Rooftop",
    "Rotunda",
    "Salon",
    "Screening Room",
    "Shopping Center",
    "Skybox",
    "Soundstage",
    "Sports Complex",
    "Stadium",
    "Stage",
    "Station",
    "Studio",
    "Suite",
    "Sundeck",
    "Tea Room",
    "Terrace",
    "Theater",
    "TV Studio",
    "Warehouse",
    "White Box",
    "Winery",
    "Work Area"
];